[package]
name = "njwt"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "njwt"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.21.1"
lazy_static = "1.0"
jsonwebtoken = "7"
serde = {version = "1.0", features = ["derive"]}

